package edu.utap.kal.model

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

// Firebase insists we have a no argument constructor
data class Note(
    // AuthWrap information
    var name: String = "",
    var ownerUid: String = "",
    // Text
    var text: String = "",
    var pictureUUIDs: List<String> = listOf(),
    var category: String = "",
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // FirestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
)
